#pragma once

#define ENUMERATE_TWO_ITEMS(NEXT, X) X, NEXT(X)
#define ENUMERATE_FOUR_ITEMS(NEXT, X) ENUMERATE_TWO_ITEMS(NEXT, X), ENUMERATE_TWO_ITEMS(NEXT, NEXT(NEXT(X))) 
#define ENUMERATE_EIGHT_ITEMS(NEXT, X) ENUMERATE_FOUR_ITEMS(NEXT, X), ENUMERATE_FOUR_ITEMS(NEXT, NEXT(NEXT(NEXT(NEXT(X)))))

#define ENUMERATE_FUNC_2_ELEMENTS(FUNC, X) FUNC(X), FUNC(X + 1)
#define ENUMERATE_FUNC_4_ELEMENTS(FUNC, X) ENUMERATE_FUNC_2_ELEMENTS(FUNC, X), ENUMERATE_FUNC_2_ELEMENTS(FUNC, X + 2)
#define ENUMERATE_FUNC_8_ELEMENTS(FUNC, X) ENUMERATE_FUNC_4_ELEMENTS(FUNC, X), ENUMERATE_FUNC_4_ELEMENTS(FUNC, X + 4)
#define ENUMERATE_FUNC_16_ELEMENTS(FUNC, X) ENUMERATE_FUNC_8_ELEMENTS(FUNC, X), ENUMERATE_FUNC_8_ELEMENTS(FUNC, X + 8)
#define ENUMERATE_FUNC_32_ELEMENTS(FUNC, X) ENUMERATE_FUNC_16_ELEMENTS(FUNC, X), ENUMERATE_FUNC_16_ELEMENTS(FUNC, X + 16)
#define ENUMERATE_FUNC_64_ELEMENTS(FUNC, X) ENUMERATE_FUNC_32_ELEMENTS(FUNC, X), ENUMERATE_FUNC_32_ELEMENTS(FUNC, X + 32)
#define ENUMERATE_FUNC_128_ELEMENTS(FUNC, X) ENUMERATE_FUNC_64_ELEMENTS(FUNC, X), ENUMERATE_FUNC_64_ELEMENTS(FUNC, X + 64)
#define ENUMERATE_FUNC_256_ELEMENTS(FUNC, X) ENUMERATE_FUNC_128_ELEMENTS(FUNC, X), ENUMERATE_FUNC_128_ELEMENTS(FUNC, X + 128)


#define __IN_RANGE8(X) ( 0 <= X && X < 8)

#define MAX_SPELL_COUNT 10
#define FREEZE 0
#define JUMP 1
#define FREEZE_COOLDOWN 2
#define JUMP_COOLDOWN 2


#define CUSTOM_EXCEPTION(X) class X : public std::exception { std::string message; \
public: \
	X(const std::string msg) : message(msg) {};  \
	const char* what() const noexcept override { return message.c_str(); }\
};
